runtime: nodejs20
service: default
entrypoint: node app.js
env_variables:
  NODE_ENV: production
  MONGO_URI: [YOUR_MONGO_URI]
  JWT_SECRET: [YOUR_JWT_SECRET]
  ARTSY_CLIENT_ID: [YOUR_ARTSY_CLIENT_ID]
  ARTSY_CLIENT_SECRET: [YOUR_ARTSY_CLIENT_SECRET]
